### PR TITLE
Proposal to remove max statements

### PR DESCRIPTION
**Pull request by antiBaconMachine**
It's just a proposal people, lets keep it civil!

I don't personally like this rule, I've heard other people have issues with it also, here's 1 possible solution.

### CODE REVIEW

**Comment by allouis** [comment]
:+1: LGTM

**Comment by qubyte** [comment]
Sorry 👎

**Comment by qubyte** [comment]
(I encourage you to turn max-statements off in tests though)

**Comment by allouis** [comment]
> Sorry 👎

Does this mean you're not happy to merge this, even if the majority of the team would prefer this behaviour? 

I feel like we've had a lot of issues within the team about linter rules and maybe the best way to solve them is by proposal PR's like this where people can throw out ideas and see what the rest of the team think :shrug: 

I would encourage @vizia/vizia-dev to take a look at this

**Comment by qubyte** [comment]
I'm open to changes to the linter rules where the behaviour is unexpected. In this case, the behaviour is intended. Lots of statements means hard to grok code.

Please note, while suggestions are welcome, this is not a democracy. The point of this is to enforce some consistency and avoid too many discussions on style. If each proposal becomes a long thread, we're missing the point.

**Comment by cham** [comment]
I'm also in favor of removing this rule, but as Mark says it is ultimately his decision. You can override this per-file / function if you need to, right?

**Pull request closed without merging**
